# .github/workflows/firebase.yml
name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Generate images.json
        run: node public/generate-json.js

      - name: Build (Firebase or other)
        run: npm run build # or your build command

      - name: Deploy to Firebase Hosting
        run: npx firebase-tools deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}